// <auto-generated />
using System;
using Boc.Assets.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Boc.Assets.Infrastructure.Migrations.app
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Boc.Assets.Domain.Models.Applies.AssetApply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetCategoryId");

                    b.Property<string>("AssetCategoryThirdLevel");

                    b.Property<string>("LastModifiedContent");

                    b.Property<string>("Message");

                    b.Property<Guid>("RequestOrgId");

                    b.Property<string>("RequestOrgIdentifier")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("RequestOrgNam")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Status");

                    b.Property<Guid>("TargetOrgId");

                    b.Property<string>("TargetOrgIdentifier")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("TargetOrgNam")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("AssetApplies");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Applies.AssetExchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetId");

                    b.Property<string>("AssetName");

                    b.Property<Guid>("ExchangeOrgId");

                    b.Property<string>("ExchangeOrgIdentifier")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ExchangeOrgNam")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastModifiedContent");

                    b.Property<string>("Message");

                    b.Property<Guid>("RequestOrgId");

                    b.Property<string>("RequestOrgIdentifier")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("RequestOrgNam")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Status");

                    b.Property<Guid>("TargetOrgId");

                    b.Property<string>("TargetOrgIdentifier")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("TargetOrgNam")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("AssetExchanges");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Applies.AssetReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetId");

                    b.Property<string>("AssetName");

                    b.Property<string>("LastModifiedContent");

                    b.Property<string>("Message");

                    b.Property<Guid>("RequestOrgId");

                    b.Property<string>("RequestOrgIdentifier")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("RequestOrgNam")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Status");

                    b.Property<Guid>("TargetOrgId");

                    b.Property<string>("TargetOrgIdentifier")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("TargetOrgNam")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("AssetReturns");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.AssetInventories.AssetInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<DateTime>("ExpiryDateTime");

                    b.Property<Guid>("PublisherId");

                    b.Property<string>("PublisherIdentifier")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PublisherOrg2")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("TaskComment")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("AssetInventories");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.AssetInventories.AssetInventoryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetId");

                    b.Property<string>("AssetInventoryLocation")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("AssetInventoryRegisterId");

                    b.Property<int>("InventoryStatus");

                    b.Property<string>("ResponsibilityIdentity")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ResponsibilityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ResponsibilityOrg2")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetInventoryRegisterId");

                    b.ToTable("AssetInventoryDetails");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.AssetInventories.AssetInventoryRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetInventoryId");

                    b.Property<Guid>("ParticipationId");

                    b.HasKey("Id");

                    b.HasIndex("AssetInventoryId");

                    b.HasIndex("ParticipationId");

                    b.ToTable("AssetInventoryRegisters");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AssetCategoryId");

                    b.Property<string>("AssetDescription")
                        .HasMaxLength(100);

                    b.Property<string>("AssetLocation");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AssetNo")
                        .HasMaxLength(100);

                    b.Property<int>("AssetStatus");

                    b.Property<string>("AssetTagNumber")
                        .HasMaxLength(50);

                    b.Property<string>("AssetType")
                        .HasMaxLength(100);

                    b.Property<string>("Brand")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CreateDateTime");

                    b.Property<DateTime?>("InStoreDateTime");

                    b.Property<string>("LastDeployRecord")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LastModifyDateTime");

                    b.Property<string>("OrgInUseIdentifier")
                        .HasMaxLength(20);

                    b.Property<string>("OrgInUseName")
                        .HasMaxLength(50);

                    b.Property<Guid?>("OrganizationInChargeId");

                    b.Property<Guid?>("OrganizationInUseId");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("OrganizationInChargeId");

                    b.HasIndex("OrganizationInUseId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssetFirstLevelCategory")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("AssetMeteringUnit");

                    b.Property<string>("AssetSecondLevelCategory")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("AssetThirdLevelCategory")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("AssetCategories");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.AssetDeploy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AssetDeployCategory");

                    b.Property<Guid>("AssetId");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AssetNo")
                        .HasMaxLength(50);

                    b.Property<string>("AssetTagNumber")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreateDateTime");

                    b.HasKey("Id");

                    b.ToTable("AssetDeploys");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.CategoryManageRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetCategoryId");

                    b.Property<Guid>("ManagerId");

                    b.Property<string>("Org2")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("ManagerId");

                    b.ToTable("CategoryManageRegisters");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.Maintainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssetCategoryId");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MaintainerName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(20);

                    b.Property<string>("Org2")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<Guid>("OrganizationId");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("Maintainers");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Organizations.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(20);

                    b.Property<string>("Org2");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Hash");

                    b.Property<string>("Org1")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Org2")
                        .HasMaxLength(10);

                    b.Property<string>("Org3")
                        .HasMaxLength(10);

                    b.Property<string>("OrgIdentifier");

                    b.Property<string>("OrgLvl")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("OrgNam")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("OrgNam1")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("OrgNam2")
                        .HasMaxLength(100);

                    b.Property<string>("OrgNam3")
                        .HasMaxLength(100);

                    b.Property<string>("OrgShortNam")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("RoleId");

                    b.Property<byte[]>("Salt");

                    b.Property<int>("Status");

                    b.Property<string>("UpOrg")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("OrgIdentifier")
                        .IsUnique()
                        .HasFilter("[OrgIdentifier] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Organizations.OrganizationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.ToTable("OrganizationRoles");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Organizations.OrganizationSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("OrgId");

                    b.Property<string>("OrgIdentifier");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SpaceDescription")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SpaceName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("OrganizationSpaces");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Organizations.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.AssetInventories.AssetInventoryDetail", b =>
                {
                    b.HasOne("Boc.Assets.Domain.Models.Assets.Asset", "Asset")
                        .WithMany("AssetInventoryDetails")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boc.Assets.Domain.Models.AssetInventories.AssetInventoryRegister", "AssetInventoryRegister")
                        .WithMany("AssetInventoryDetails")
                        .HasForeignKey("AssetInventoryRegisterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.AssetInventories.AssetInventoryRegister", b =>
                {
                    b.HasOne("Boc.Assets.Domain.Models.AssetInventories.AssetInventory", "AssetInventory")
                        .WithMany("AssetInventoryRegisters")
                        .HasForeignKey("AssetInventoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boc.Assets.Domain.Models.Organizations.Organization", "Participation")
                        .WithMany("AssetInventoryRegisters")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.Asset", b =>
                {
                    b.HasOne("Boc.Assets.Domain.Models.Assets.AssetCategory", "AssetCategory")
                        .WithMany("Assets")
                        .HasForeignKey("AssetCategoryId");

                    b.HasOne("Boc.Assets.Domain.Models.Organizations.Organization", "OrganizationInCharge")
                        .WithMany("AssetsInCharge")
                        .HasForeignKey("OrganizationInChargeId");

                    b.HasOne("Boc.Assets.Domain.Models.Organizations.Organization", "OrganizationInUse")
                        .WithMany("AssetsInUse")
                        .HasForeignKey("OrganizationInUseId");
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.AssetDeploy", b =>
                {
                    b.OwnsOne("Boc.Assets.Domain.ValueObjects.OrganizationInfo", "AuthorizeOrgInfo", b1 =>
                        {
                            b1.Property<Guid>("AssetDeployId");

                            b1.Property<Guid>("OrgId");

                            b1.Property<string>("OrgIdentifier")
                                .IsRequired()
                                .HasMaxLength(20);

                            b1.Property<string>("OrgNam")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.HasKey("AssetDeployId");

                            b1.ToTable("AssetDeploys");

                            b1.HasOne("Boc.Assets.Domain.Models.Assets.AssetDeploy")
                                .WithOne("AuthorizeOrgInfo")
                                .HasForeignKey("Boc.Assets.Domain.ValueObjects.OrganizationInfo", "AssetDeployId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Boc.Assets.Domain.ValueObjects.OrganizationInfo", "ExportOrgInfo", b1 =>
                        {
                            b1.Property<Guid>("AssetDeployId");

                            b1.Property<Guid>("OrgId");

                            b1.Property<string>("OrgIdentifier")
                                .IsRequired()
                                .HasMaxLength(20);

                            b1.Property<string>("OrgNam")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.HasKey("AssetDeployId");

                            b1.ToTable("AssetDeploys");

                            b1.HasOne("Boc.Assets.Domain.Models.Assets.AssetDeploy")
                                .WithOne("ExportOrgInfo")
                                .HasForeignKey("Boc.Assets.Domain.ValueObjects.OrganizationInfo", "AssetDeployId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Boc.Assets.Domain.ValueObjects.OrganizationInfo", "ImportOrgInfo", b1 =>
                        {
                            b1.Property<Guid>("AssetDeployId");

                            b1.Property<Guid>("OrgId");

                            b1.Property<string>("OrgIdentifier")
                                .IsRequired()
                                .HasMaxLength(20);

                            b1.Property<string>("OrgNam")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.HasKey("AssetDeployId");

                            b1.ToTable("AssetDeploys");

                            b1.HasOne("Boc.Assets.Domain.Models.Assets.AssetDeploy")
                                .WithOne("ImportOrgInfo")
                                .HasForeignKey("Boc.Assets.Domain.ValueObjects.OrganizationInfo", "AssetDeployId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.CategoryManageRegister", b =>
                {
                    b.HasOne("Boc.Assets.Domain.Models.Assets.AssetCategory", "AssetCategory")
                        .WithMany("CategoryManageRegisters")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boc.Assets.Domain.Models.Organizations.Organization", "Manager")
                        .WithMany("CategoryManageRegisters")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Assets.Maintainer", b =>
                {
                    b.HasOne("Boc.Assets.Domain.Models.Assets.AssetCategory", "AssetCategory")
                        .WithMany("Maintainers")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Organizations.Organization", b =>
                {
                    b.HasOne("Boc.Assets.Domain.Models.Organizations.OrganizationRole", "Role")
                        .WithMany("Organizations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Organizations.OrganizationSpace", b =>
                {
                    b.HasOne("Boc.Assets.Domain.Models.Organizations.Organization", "Organization")
                        .WithMany("OrganizationSpaces")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boc.Assets.Domain.Models.Organizations.Permission", b =>
                {
                    b.HasOne("Boc.Assets.Domain.Models.Organizations.OrganizationRole", "OrganizationRole")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
